title: Julie Pew
logo: /assets/portfolio.jpg
description: Welcome to the CS 499 Capstone project as presented in the form of an ePortfolio. This portfolio is the culmination of my hard work, dedication, and academic career at Southern New Hampshire University.
show_downloads: false
theme: jekyll-theme-minimal
